@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sat Apr 25 23:12:18 +0500 2026
REM SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim forwarding_tb_behav -key {Behavioral:sim_1:Functional:forwarding_tb} -tclbatch forwarding_tb.tcl -view E:/Habib/Sem 4/CA/CA_Pipelining_Project/Pipelining-Project/forwarding_tb_behav.wcfg -log simulate.log"
call xsim  forwarding_tb_behav -key {Behavioral:sim_1:Functional:forwarding_tb} -tclbatch forwarding_tb.tcl -view E:/Habib/Sem 4/CA/CA_Pipelining_Project/Pipelining-Project/forwarding_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
